import {useEffect,useState} from 'react'; import {api} from '../lib/api';
type Lesson={id:string;section:string;title:string;level:string;summary:string;steps:string[];question:string;options:string[];answer:number;explanation:string};
export default function Lessons(){
 const [items,setItems]=useState<Lesson[]>([]),[active,setActive]=useState<Lesson|null>(null),[running,setRunning]=useState(false),[step,setStep]=useState(0),[choice,setChoice]=useState<number|null>(null),[error,setError]=useState('');
 useEffect(()=>{api<Lesson[]>('/api/lessons').then(x=>{setItems(x);setActive(x[0]||null)}).catch(e=>setError(String(e)))},[]);
 function start(l=active){if(!l)return;setActive(l);setRunning(true);setStep(0);setChoice(null)}
 if(running&&active)return <div className="lessonRunner card"><button className="backBtn" onClick={()=>setRunning(false)}>← К УРОКАМ</button><span className="tag">{active.section} // {active.level}</span><h2>{active.title}</h2><p>{active.summary}</p>{step<active.steps.length?<><div className="lessonProgress">ШАГ {step+1}/{active.steps.length}</div><div className="lessonStep">{active.steps[step]}</div><button className="primary" onClick={()=>setStep(step+1)}>{step===active.steps.length-1?'К ПРОВЕРКЕ':'ДАЛЬШЕ'}</button></>:<><div className="lessonProgress">ПРОВЕРКА</div><h3>{active.question}</h3><div className="quizOptions">{active.options.map((o,i)=><button key={o} className={choice===i?'quiz selected':'quiz'} onClick={()=>setChoice(i)}>{o}</button>)}</div>{choice!==null&&<div className={choice===active.answer?'result ok':'result bad'}><b>{choice===active.answer?'ВЕРНО':'НЕВЕРНО'}</b><p>{active.explanation}</p></div>}<button className="secondary" onClick={()=>{setRunning(false);setChoice(null)}}>ЗАВЕРШИТЬ УРОК</button></>}</div>;
 return <div><div className="sectionIntro"><h2>УРОКИ // {items.length}</h2><p>Короткая теория → алгоритм → проверка. Никаких неработающих карточек: каждый урок можно пройти прямо сейчас.</p></div>{error&&<div className="warning">{error}</div>}<div className="lessonGrid">{items.map(l=><button className={active?.id===l.id?'lessonCard active':'lessonCard'} onClick={()=>setActive(l)} key={l.id}><span className="tag">{l.section}</span><h3>{l.title}</h3><p>{l.summary}</p><small>{l.level}</small><span className="lessonGo" onClick={(e)=>{e.stopPropagation();start(l)}}>НАЧАТЬ →</span></button>)}</div>{active&&<div className="lessonDock"><div><span className="tag">ВЫБРАНО</span><b>{active.title}</b></div><button className="primary" onClick={()=>start()}>НАЧАТЬ УРОК</button></div>}</div>
}
