import {useEffect,useMemo,useState} from 'react';
import {Chess} from 'chess.js';
import {Chessboard} from 'react-chessboard';
import {api} from '../lib/api';
import {uciRu} from '../lib/chessNotation';

type O={eco:string;name_ru:string;name_en:string;moves:string;pgn?:string;line_uci?:string[];side:string;style:string[];difficulty:number;theory:number;elo_min:number;when:string;why:string;plan_white:string[];plan_black:string[];next:string[];source?:string};
type Side='white'|'black';

function OpeningTrainer({opening,onClose}:{opening:O;onClose:()=>void}){
 const [side,setSide]=useState<Side>('white'),[game,setGame]=useState(new Chess()),[idx,setIdx]=useState(0),[msg,setMsg]=useState(''),[hint,setHint]=useState(0);
 const line=opening.line_uci||[];
 function reset(nextSide=side){const g=new Chess();let i=0;if(nextSide==='black'&&line[0]){const u=line[0];try{g.move({from:u.slice(0,2),to:u.slice(2,4),promotion:u[4]||'q'} as any);i=1}catch{}}setSide(nextSide);setGame(g);setIdx(i);setMsg('');setHint(0)}
 useEffect(()=>reset(side),[opening.name_en]);
 const expected=line[idx];
 function drop(s:string,t:string){if(!expected)return false;const u=s+t;if(!expected.startsWith(u)){setMsg('ЭТО ДРУГОЙ ВАРИАНТ // в этом тренажёре пока отрабатываем выбранную основную линию.');return false}
   const next=new Chess(game.fen());try{next.move({from:s,to:t,promotion:expected[4]||'q'} as any)}catch{return false};let ni=idx+1;setGame(next);setMsg('ТОЧНО');setHint(0);
   if(ni<line.length){setTimeout(()=>{const reply=line[ni];const g2=new Chess(next.fen());try{g2.move({from:reply.slice(0,2),to:reply.slice(2,4),promotion:reply[4]||'q'} as any);setGame(g2);setIdx(ni+1);setMsg('Ответ соперника сделан. Твой ход.')}catch{setIdx(ni)}},250)}else setIdx(ni);return true}
 const hintText=expected?hint===1?'Вспомни идею дебюта и посмотри, какую фигуру логично развить.':hint===2?`Ищи ход фигурой с ${expected.slice(0,2)}.`:hint>=3?`ТОЧНЫЙ ХОД // ${uciRu(game,expected)}`:'' : '';
 return <div><button className="backBtn" onClick={onClose}>← К ЭНЦИКЛОПЕДИИ</button><div className="sectionIntro compact"><div className="sectionCode">OPENING//TRAIN</div><h2>{opening.name_ru}</h2><p>{opening.name_en} · основная линия из открытого ECO-каталога.</p></div><div className="gameToolbar"><div className="segmented"><span>ИГРАЮ</span><button className={side==='white'?'selected':''} onClick={()=>reset('white')}>БЕЛЫМИ</button><button className={side==='black'?'selected':''} onClick={()=>reset('black')}>ЧЁРНЫМИ</button></div><div className="turnStatus">ШАГ // {Math.min(idx+1,line.length)}/{line.length}</div></div><div className="trainingPlay"><section className="boardCard"><div className="boardFrame"><Chessboard options={{position:game.fen(),boardOrientation:side,onPieceDrop:({sourceSquare,targetSquare})=>!!targetSquare&&drop(sourceSquare,targetSquare),boardStyle:{borderRadius:'0',boxShadow:'none'}}}/></div></section><aside className="card trainingPrompt"><span className="tag">{opening.eco}</span><h2>{idx>=line.length?'ЛИНИЯ ПРОЙДЕНА':'ТВОЙ ХОД'}</h2><p>{idx>=line.length?'Ты воспроизвёл основную линию. Теперь можно сменить сторону или выбрать другой вариант.':opening.why}</p>{expected&&<><button className="secondary" onClick={()=>setHint(h=>Math.min(3,h+1))}>ПОДСКАЗКА {Math.min(hint+1,3)}/3</button>{hintText&&<div className="hint">{hintText}</div>}</>}{msg&&<div className={msg==='ТОЧНО'?'result ok':'status'}>{msg}</div>}<div className="moves"><b>ЛИНИЯ</b><br/>{opening.moves}</div><button className="secondary" onClick={()=>reset(side)}>СНАЧАЛА</button></aside></div></div>
}

export default function Openings(){
 const [list,setList]=useState<O[]>([]),[q,setQ]=useState(''),[active,setActive]=useState<O|null>(null),[trainer,setTrainer]=useState<O|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{api<O[]>('/api/openings?limit=5000').then(x=>{setList(x);setActive(x[0]||null)}).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>list.filter(o=>(o.name_ru+o.name_en+o.eco).toLowerCase().includes(q.toLowerCase())).slice(0,350),[q,list]);
 if(trainer)return <OpeningTrainer opening={trainer} onClose={()=>setTrainer(null)}/>;
 return <div><div className="sectionIntro openingHeader"><div><div className="sectionCode">ECO//CC0</div><h2>ЭНЦИКЛОПЕДИЯ // {loading?'…':list.length}</h2><p>Каталог автоматически берётся из открытой базы Lichess chess-openings. Поиск работает по ECO, русскому и международному названию.</p></div></div><div className="openingLayout"><section><input className="search" placeholder="ПОИСК: название / ECO / variation" value={q} onChange={e=>setQ(e.target.value)}/><small className="sourceLine">ПОКАЗАНО {filtered.length} ИЗ {list.length} · уточни поиск для редких вариантов</small><div className="openingList">{filtered.map((o,i)=><button key={o.eco+o.name_en+i} className={active===o?'openingRow active':'openingRow'} onClick={()=>setActive(o)}><span>{o.eco}</span><div><b>{o.name_ru}</b><small>{o.name_en}</small></div></button>)}</div></section><aside className="detail card openingDetail">{active&&<><div className="tags"><span className="tag">{active.eco}</span>{active.style.map(s=><span className="tag muted" key={s}>{s}</span>)}</div><h2>{active.name_ru}</h2><small>{active.name_en}</small><div className="moves">{active.moves}</div><div className="openingMeta"><span>СЛОЖНОСТЬ {active.difficulty}/5</span><span>ТЕОРИЯ {active.theory}/5</span><span>ОТ {active.elo_min} ELO</span></div><h4>КОГДА ИГРАТЬ</h4><p>{active.when}</p><h4>ЗАЧЕМ</h4><p>{active.why}</p><div className="split"><div><h4>ПЛАН БЕЛЫХ</h4><ul>{active.plan_white.map(x=><li key={x}>{x}</li>)}</ul></div><div><h4>ПЛАН ЧЁРНЫХ</h4><ul>{active.plan_black.map(x=><li key={x}>{x}</li>)}</ul></div></div><button className="primary" disabled={!active.line_uci?.length} onClick={()=>setTrainer(active)}>ТРЕНИРОВАТЬ НА ДОСКЕ →</button><small className="sourceLine">SOURCE // {active.source||'локальный каталог'}</small></>}</aside></div></div>
}
